---
name: Code Quality Checks
on:
  - push
  - pull_request

jobs:
  lint:
    runs-on: ubuntu-22.04
    env:
      CI: 'true'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - run: make install
      - run: make lint
